//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfUtility_Call.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfUtility_Call.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Apply に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Button_Apply {
            get {
                return ResourceManager.GetString("Dialog_Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Button_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Dialog_Button_OK {
            get {
                return ResourceManager.GetString("Dialog_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   collapse Ribbon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_button_Minimize_ToolTip_Hide {
            get {
                return ResourceManager.GetString("MainWindow_button_Minimize_ToolTip_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   expand Ribbon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_button_Minimize_ToolTip_Show {
            get {
                return ResourceManager.GetString("MainWindow_button_Minimize_ToolTip_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Orientation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_comboBox_PageOrientation_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_comboBox_PageOrientation_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_comboBox_PageSize_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_comboBox_PageSize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Printer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_comboBox_Printer_ToolTip {
            get {
                return ResourceManager.GetString("MainWindow_comboBox_Printer_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use System Dialog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_comboBox_Printer_UseSystemDialog {
            get {
                return ResourceManager.GetString("MainWindow_comboBox_Printer_UseSystemDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Page に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_group_Page_Header {
            get {
                return ResourceManager.GetString("MainWindow_group_Page_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_group_Print_Header {
            get {
                return ResourceManager.GetString("MainWindow_group_Print_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_group_PrintColor {
            get {
                return ResourceManager.GetString("MainWindow_group_PrintColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Printer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_group_Printer_Header {
            get {
                return ResourceManager.GetString("MainWindow_group_Printer_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Monitor DPI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_menuItem_ShowMonitorDpi_Header {
            get {
                return ResourceManager.GetString("MainWindow_menuItem_ShowMonitorDpi_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language setting will work after restart. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_method_SetCulture_message_OK {
            get {
                return ResourceManager.GetString("MainWindow_method_SetCulture_message_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [R_en] Mac(CR) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_NewLineCodes_Cr {
            get {
                return ResourceManager.GetString("MainWindow_NewLineCodes_Cr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [R_en] Unix(LF) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_NewLineCodes_Lf {
            get {
                return ResourceManager.GetString("MainWindow_NewLineCodes_Lf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_tab_Print_Header {
            get {
                return ResourceManager.GetString("MainWindow_tab_Print_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Buttons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_tab_TrExtension_group_Buttons_Header {
            get {
                return ResourceManager.GetString("MainWindow_tab_TrExtension_group_Buttons_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainWindow_tab_TrExtension_group_Culture_Header {
            get {
                return ResourceManager.GetString("MainWindow_tab_TrExtension_group_Culture_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   First Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Person_FirstName {
            get {
                return ResourceManager.GetString("Person_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Full Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Person_FullName {
            get {
                return ResourceManager.GetString("Person_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Person_ID {
            get {
                return ResourceManager.GetString("Person_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Person_LastName {
            get {
                return ResourceManager.GetString("Person_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Person_Sex {
            get {
                return ResourceManager.GetString("Person_Sex", resourceCulture);
            }
        }
    }
}
