using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using TakeAshUtility;

namespace WpfUtility {

    public class DataGridEx : DataGrid {

        static DataGridEx() {
            DefaultStyleKeyProperty.OverrideMetadata(
                typeof(DataGridEx),
                new FrameworkPropertyMetadata(typeof(DataGridEx))
            );
        }

        public DataGridEx()
            : base() {

            _columnNames = new List<string>();
            _autoFilterItems = new Dictionary<string, AutoFilterItem>();
            var collectionView = CollectionViewSource.GetDefaultView(this.Items) as CollectionView;
            ((INotifyCollectionChanged)collectionView).CollectionChanged += OnUpdateItems;
            collectionView.Filter = PredicateAutoFilter;
            ColumnHeaderStyle = new Style();
            AutoGeneratedColumns += OnAutoGeneratedColumns;
        }

        private List<string> _columnNames;
        private Dictionary<string, AutoFilterItem> _autoFilterItems;

        public void UpdateAutoFilter() {
            if (Items == null) {
                return;
            }
            if (_columnNames.Count == 0) {
                foreach (var item in Items) {
                    var pis = item.GetType()
                        .GetProperties(BindingFlags.Instance | BindingFlags.Public)
                        .Where(pi => pi.GetIndexParameters().Length == 0)
                        .ToList();
                    if (pis == null || pis.Count == 0) {
                        continue;
                    }
                    pis.ForEach(pi => {
                        if (!_autoFilterItems.ContainsKey(pi.Name)) {
                            _autoFilterItems[pi.Name] = new AutoFilterItem(pi.Name, this);
                        }
                        var value = pi.GetValue(item, null).SafeToString(null);
                        if (value != null &&
                            !_autoFilterItems[pi.Name].Values.ContainsKey(value)) {
                            _autoFilterItems[pi.Name].Values[value] = true;
                        }
                    });
                }
            } else {
                _columnNames.ForEach(column => {
                    foreach (var item in Items) {
                        var pi = item.GetType()
                            .GetProperty(column, BindingFlags.Instance | BindingFlags.Public);
                        if (pi == null) {
                            continue;
                        }
                        var value = pi.GetValue(item, null).SafeToString(null);
                        if (value != null &&
                            !_autoFilterItems[column].Values.ContainsKey(value)) {
                            _autoFilterItems[column].Values[value] = true;
                        }
                    }
                    var menu = _autoFilterItems[column].Menu;
                    menu.Items.Clear();
                    menu.Items.Add<UIElement>(CreateInitialAutoFilterMenuItems(column));
                    if (_autoFilterItems.ContainsKey(column)) {
                        menu.Items.Add<UIElement>(_autoFilterItems[column]
                            .Values
                            .Keys
                            .OrderBy(item => item)
                            .Select(item => CreateValueSelectCheckBox(column, item))
                        );
                    }
                });
            }
        }

        private List<UIElement> CreateInitialAutoFilterMenuItems(string column) {
            var checkBoxAll = new CheckBox() {
                Content = "All",
                IsChecked = !_autoFilterItems.ContainsKey(column) ?
                    true :
                    _autoFilterItems[column].Values.Aggregate(true, (current, kvp) => current && kvp.Value),
            };
            checkBoxAll.Checked += (sender, e) => {
                var checkBox0 = sender as CheckBox;
                _autoFilterItems[column].Menu
                    .Items
                    .OfType<CheckBox>()
                    .Where(checkBox => checkBox != checkBox0)
                    .ToList()
                    .ForEach(checkBox => {
                        checkBox.IsChecked = true;
                    });
            };
            return new List<UIElement>() {
                checkBoxAll,
                new Separator(),
            };
        }

        private CheckBox CreateValueSelectCheckBox(string column, string item) {
            var checkBox = new CheckBox() {
                Content = item,
                IsChecked = _autoFilterItems[column].Values[item],
            };
            checkBox.Checked += (sender, e) => {
                _autoFilterItems[column].Values[item] = true;
            };
            checkBox.Unchecked += (sender, e) => {
                _autoFilterItems[column].Values[item] = false;
                var checkBoxAll = _autoFilterItems[column].Menu.Items[0] as CheckBox;
                checkBoxAll.IsChecked = false;
            };
            return checkBox;
        }

        private bool PredicateAutoFilter(object item) {
            if (_autoFilterItems == null) {
                return true;
            }
            foreach (var p in _autoFilterItems.Keys) {
                foreach (var kvp in _autoFilterItems[p].Values) {
                    if (kvp.Value == true) {
                        continue;
                    }
                    var pi = item.GetType().GetProperty(p, BindingFlags.Instance | BindingFlags.Public);
                    var value = pi.GetValue(item, null).SafeToString();
                    if (value != null && value == kvp.Key) {
                        return false;
                    }
                }
            }
            return true;
        }

        private void OnUpdateItems(object sender, NotifyCollectionChangedEventArgs e) {
            UpdateAutoFilter();
        }

        private void OnAutoGeneratedColumns(object sender, EventArgs e) {
            if (ColumnHeaderStyle.Triggers.IsSealed) {
                return;
            }
            this.Columns
                .ToList()
                .ForEach(column => {
                    var name = column.Header.ToString();
                    _columnNames.Add(name);
                    var menu = new ContextMenu();
                    menu.Closed += (s, args) => {
                        var source = this.ItemsSource;
                        this.ItemsSource = null;
                        this.ItemsSource = source;
                    };
                    menu.Items.Add<UIElement>(CreateInitialAutoFilterMenuItems(name));
                    if (_autoFilterItems.ContainsKey(name)) {
                        menu.Items.Add<UIElement>(_autoFilterItems[name]
                            .Values
                            .OrderBy(item => item.Key)
                            .Select(item => CreateValueSelectCheckBox(name, item.Key))
                        );
                    }
                    if (!_autoFilterItems.ContainsKey(name)) {
                        _autoFilterItems[name] = new AutoFilterItem(name, this);
                    }
                    _autoFilterItems[name].Menu = menu;
                    ColumnHeaderStyle.Triggers.Add(_autoFilterItems[name].HeaderTrigger);
                });
        }

        private class AutoFilterItem {

            public AutoFilterItem(string name, DataGrid dataGrid) {
                Name = name;
                Menu = new ContextMenu();
                Menu.Closed += (s, args) => {
                    var source = dataGrid.ItemsSource;
                    dataGrid.ItemsSource = null;
                    dataGrid.ItemsSource = source;
                };
                Values = new Dictionary<string, bool>();
            }

            public string Name { get; set; }
            public ContextMenu Menu { get; set; }
            public Dictionary<string, bool> Values { get; set; }

            public Trigger HeaderTrigger {
                get {
                    return new Trigger() {
                        Property = DataGridColumnHeader.ContentProperty,
                        Value = Name,
                        Setters = { new Setter(DataGridColumnHeader.ContextMenuProperty, Menu), },
                    };
                }
            }
        }
    }
}
